// Copyright (c) 2026 Eitanity Systems VCC. All rights reserved.
// Use of this source code is governed by the BSD-2-Clause licence in LICENSE.

package softmagic

import (
	"unicode/utf8"

	"github.com/eitanity/softmagic/internal/invariant"
)

// printRange is a run of code points glibc's iswprint accepts in a UTF-8
// locale, all of one width: wcwidth's, or one where that is zero.
type printRange struct {
	lo, hi rune
	width  int
}

// iswprint is glibc's iswprint in a UTF-8 locale, read from printRanges
// (wctype.go, generated by make wctype).
func iswprint(r rune) bool {
	invariant.Check(len(printRanges) > 0, "iswprint table present")
	lo, hi := 0, len(printRanges)
	// A binary search over fewer than 2^32 runs ends within 32 halvings.
	for step := 0; step < 32 && lo < hi; step++ {
		mid := int(uint(lo+hi) >> 1)
		p := printRanges[mid] // run
		switch {
		case r < p.lo:
			hi = mid
		case r > p.hi:
			lo = mid + 1
		default:
			return p.width > 0
		}
	}
	return false
}

// escapeResult is file_getbuffer, which the reference applies to every
// answer it returns unless MAGIC_RAW is set: in a buffer that is valid
// UTF-8, a character iswprint rejects becomes the \ooo escapes of its
// bytes; in one that is not, every byte outside printable ASCII does.
// Each list is escaped as the one buffer the reference prints it in.
// Failure buffers are left as they are: the reference prints magic_error
// without this step.
func escapeResult(r Result) Result {
	invariant.Check(r.Description != "", "a blank is never an answer")
	r.Description = escapeText(r.Description, utf8.ValidString(r.Description))
	r.MIME = escapeText(r.MIME, utf8.ValidString(r.MIME))
	r.Charset = escapeText(r.Charset, utf8.ValidString(r.Charset))
	r.Apple = escapeText(r.Apple, utf8.ValidString(r.Apple))
	r.Extensions = escapeList(r.Extensions)
	c := &r.Continued // continued
	c.Descriptions = escapeList(c.Descriptions)
	c.MIMEs = escapeList(c.MIMEs)
	c.Encodings = escapeList(c.Encodings)
	c.Extensions = escapeList(c.Extensions)
	c.Apple = escapeList(c.Apple)
	return r
}

// escapeList escapes the elements of one printed buffer, which is valid
// UTF-8 only when every element is. The list is copied before an element
// changes; an unchanged list is returned as it is.
func escapeList(list []string) []string {
	invariant.Check(len(list) <= maxOutput, "a list holds at most one element per output byte")
	valid := true
	for _, e := range list { // element
		if !utf8.ValidString(e) {
			valid = false
		}
	}
	var out []string
	for i, e := range list {
		x := escapeText(e, valid) // escaped
		if x == e {
			continue
		}
		if out == nil {
			out = append([]string(nil), list...)
		}
		out[i] = x
	}
	if out == nil {
		return list
	}
	return out
}

// escapeText escapes one string as file_getbuffer does, in its UTF-8 pass
// when valid and its byte pass otherwise. A string with nothing to escape
// is returned without copying.
func escapeText(text string, valid bool) string {
	invariant.Check(len(text) <= 4*maxOutput, "an answer is bounded by the output cap")
	if !needsEscape(text, valid) {
		return text
	}
	b := make([]byte, 0, 4*len(text)) // escaped
	if !valid {
		for i := 0; i < len(text); i++ { // byteIndex
			b = appendEscapedByte(b, text[i], cIsPrint(text[i]))
		}
		return string(b)
	}
	for i, r := range text { // byteIndex, char
		keep := iswprint(r)
		for k := i; k < i+utf8.RuneLen(r); k++ {
			b = appendEscapedByte(b, text[k], keep)
		}
	}
	return string(b)
}

// needsEscape reports whether escapeText would change text.
func needsEscape(text string, valid bool) bool {
	invariant.Check(len(text) <= 4*maxOutput, "an answer is bounded by the output cap")
	if !valid {
		for i := 0; i < len(text); i++ { // byteIndex
			if !cIsPrint(text[i]) {
				return true
			}
		}
		return false
	}
	for _, r := range text { // char
		if !iswprint(r) {
			return true
		}
	}
	return false
}

// appendEscapedByte appends c, as itself when keep, else as \ooo.
func appendEscapedByte(b []byte, c byte, keep bool) []byte {
	if keep {
		return append(b, c)
	}
	return append(b, '\\', '0'+(c>>6)&7, '0'+(c>>3)&7, '0'+c&7)
}

// hexDigit is the lower-case hex digit of v's low four bits.
func hexDigit(v byte) byte {
	invariant.Check(len(hexDigits) == 16, "sixteen hex digits")
	return hexDigits[v&0xf]
}

// appendHexByte appends c as \xHH.
func appendHexByte(b []byte, c byte) []byte {
	return append(b, '\\', 'x', hexDigit(c>>4), hexDigit(c))
}

// safeTextByte reports whether SafeText keeps a byte copied from the input.
func safeTextByte(c byte) bool {
	switch c {
	case '\\', '<', '>', '&', '"', '\'', '`':
		return false
	}
	return cIsPrint(c)
}

// fileText is SafeText's escaping of text copied from the input; without
// SafeText the text is returned as it is.
func (s *scan) fileText(text string) string {
	invariant.Check(len(text) <= 1<<20, "copied text bounded")
	if !s.safe {
		return text
	}
	return escapeHex(text, true)
}

// fileBytes is fileText for a byte slice.
func (s *scan) fileBytes(text []byte) []byte {
	invariant.Check(len(text) <= 1<<20, "copied text bounded")
	if !s.safe {
		return text
	}
	return []byte(escapeHex(string(text), true))
}

// hexKeeps reports whether escapeHex keeps c: in text copied from the
// input, what safeTextByte keeps; elsewhere, printable ASCII.
func hexKeeps(c byte, fromInput bool) bool {
	if fromInput {
		return safeTextByte(c)
	}
	return cIsPrint(c)
}

// escapeHex writes every byte hexKeeps rejects as \xHH; text with nothing
// to escape is returned without copying.
func escapeHex(text string, fromInput bool) string {
	invariant.Check(len(text) <= 1<<20, "text bounded")
	n := 0                           // escapes
	for i := 0; i < len(text); i++ { // byteIndex
		if !hexKeeps(text[i], fromInput) {
			n++
		}
	}
	if n == 0 {
		return text
	}
	b := make([]byte, 0, len(text)+3*n) // escaped
	for i := 0; i < len(text); i++ {
		if hexKeeps(text[i], fromInput) {
			b = append(b, text[i])
		} else {
			b = appendHexByte(b, text[i])
		}
	}
	return string(b)
}

// safeResult is SafeText's last step: every answer and failure buffer is
// made printable ASCII, any other byte as \xHH. Text from the input was
// escaped where it was copied; what remains is the rules' own text.
func safeResult(r Result) Result {
	invariant.Check(r.Description != "", "a blank is never an answer")
	r.Description = escapeHex(r.Description, false)
	r.MIME = escapeHex(r.MIME, false)
	r.Charset = escapeHex(r.Charset, false)
	r.Apple = escapeHex(r.Apple, false)
	r.Extensions = safeList(r.Extensions)
	r.Failures = safeFailures(r.Failures)
	c := &r.Continued // continued
	c.Descriptions = safeList(c.Descriptions)
	c.MIMEs = safeList(c.MIMEs)
	c.Encodings = safeList(c.Encodings)
	c.Extensions = safeList(c.Extensions)
	c.Apple = safeList(c.Apple)
	c.Failures = safeFailures(c.Failures)
	return r
}

// safeList is safeResult for a list, copied before an element changes.
func safeList(list []string) []string {
	invariant.Check(len(list) <= maxOutput, "a list holds at most one element per output byte")
	var out []string
	for i, e := range list { // element
		x := escapeHex(e, false) // escaped
		if x == e {
			continue
		}
		if out == nil {
			out = append([]string(nil), list...)
		}
		out[i] = x
	}
	if out == nil {
		return list
	}
	return out
}

// safeFailures is safeResult for each mode's failure buffer.
func safeFailures(f Failures) Failures {
	invariant.Check(f.Description.Buffer == "" || f.Description.Failed(), "a buffer only with a failure")
	f.Description.Buffer = escapeHex(f.Description.Buffer, false)
	f.MIME.Buffer = escapeHex(f.MIME.Buffer, false)
	f.Encoding.Buffer = escapeHex(f.Encoding.Buffer, false)
	f.Extension.Buffer = escapeHex(f.Extension.Buffer, false)
	f.Apple.Buffer = escapeHex(f.Apple.Buffer, false)
	return f
}
